<?xml version="1.0" encoding="utf-8"?><testsuites><testsuite name="pytest" errors="1" failures="0" skipped="0" tests="1" time="2.023" timestamp="2025-02-14T10:08:52.555849-08:00" hostname="W-PF4N0KDS"><testcase classname="" name="tests.api.test_contact_endpoints" time="0.000"><error message="collection failure">ImportError while importing test module 'c:\Users\D047951\Documents\GitHub\NeverEatAlone\tests\api\test_contact_endpoints.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
backend\venv\Lib\site-packages\_pytest\python.py:493: in importtestmodule
    mod = import_path(
backend\venv\Lib\site-packages\_pytest\pathlib.py:587: in import_path
    importlib.import_module(module_name)
C:\Python313\Lib\importlib\__init__.py:88: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
&lt;frozen importlib._bootstrap&gt;:1387: in _gcd_import
    ???
&lt;frozen importlib._bootstrap&gt;:1360: in _find_and_load
    ???
&lt;frozen importlib._bootstrap&gt;:1331: in _find_and_load_unlocked
    ???
&lt;frozen importlib._bootstrap&gt;:935: in _load_unlocked
    ???
backend\venv\Lib\site-packages\_pytest\assertion\rewrite.py:184: in exec_module
    exec(co, module.__dict__)
tests\api\test_contact_endpoints.py:6: in &lt;module&gt;
    from backend.app.models.contact import Contact, Hashtag, EntityType
E   ModuleNotFoundError: No module named 'backend.app.models.contact'</error></testcase></testsuite></testsuites>